.gitignore
INSTALL.md
api.lua
config.lua
nginx.conf
snapcloud_daemon

Also added `setenv` to gitignore and updated the path of start.sh
oops. :( Merge #22 first. :/

Docs Updates

---

snap-cloud-beta-0.rockspec

Fix the Rockspec URL

---

.gitmodules
nginx.conf

Add Snap! and serve from the main server.

---

bin/setup_osx.sh

Fixup macOS Install script

---

INSTALL.md
README.md
certs/README.md
discourse.lua
nginx.conf.d/http-only.conf

Improves some docs and fixes the `/nginx_status` endpoint on staging.

Minor Docs Update + basic auth tweak

---

certs/README.md
nginx.conf.d/ssl-production.conf

To be more clear about using the combined file,
and add docs about the process.

Tweak nginx cert name

---

validation.lua

This got busted when we tweaked error handling. :(

use err.x.msg in token response pages

---

api.lua
responses.lua
validation.lua

Allows showing a user is verified once they've used the token.

Show verification status if a user revisits a token URL

---

config.lua

Minor tweak to make it easier to work with writing tests

set store path when running tests

---

api.lua

This might make detecting / updating users from within Snap<em>!</em> a little nicer.

Update the session when a user is newly verified

---

nginx.conf.d/http-only.conf
nginx.conf.d/ssl-shared.conf

Minor tweaks to logging / headers

---

nginx.conf

This is really just cosmetic, but it makes the app folder slightly less distracting.

move nginx temp folders to log/

---

controllers/collection.lua
models.lua
validation.lua

This is still a WIP but it should give you a feel for the API.
Note, the auth is still removed to make testing easier.

Flesh out some collections methods

---

controllers/collection.lua
nginx.conf
nginx.conf.d/logging.conf
validation.lua

Corrects some mistakes from last night.
Fixes #132
This wasn't super urgent, but it will means we will log a lot less data
on our server.

Fix syntax errors & hide options.

---

bin/deploy.sh

Github doesn't like "false" only `false`.

Fix quotes in deploy

---

controllers/user.lua

We need this to enable Rollbar for client-side error tracking. 
(Which we are going to try to do for a while.)

Send down user id on login

---

.gitignore
app.lua
bin/deploy_certs.sh
certs/README.md
nginx.conf.d/locations.conf
nginx.conf.d/ssl-production.conf

and commit the current 'old_site' config.

Add Snap.berkeley.edu SSL support

---

Procfile
app.lua
bin/luarocks-install-macos.sh
bin/setup_osx.sh
nginx.conf.d/locations.conf

And backfill the most important snap URLs.
This probably needs a bit more testing.

Swap server homepage to be social site

---

app.lua
bin/deploy.sh
bin/deploy_certs.sh
bin/seeds.sql
controllers/collection.lua
nginx.conf.d/extensions.conf

* Add seeds so we can easily have the same collections as production
* Update Snap!Site so it has more links
* Added more into when running `bin/deploy.sh` passing in a branch or commit is optional, which makes it easy to deploy to staging.

Add a Seeds File, Update SnapSite

---

.gitignore
nginx.conf.d/locations.conf
snap-versions/README.md

Snap! Versions

---

api.lua
bin/setup_osx.sh
helpers.lua

This should reduce a bunch of errors that happen, and hopefully this message is shown.

Add GET /init since sometimes people hit it when trying to refresh a POST

---

discourse.lua
migrations.lua
models.lua

Reverts snap-cloud/snapCloud#257

Revert "Handle Users With Duplicate Emails on the forum"

---

discourse.lua
migrations.lua
models.lua

Reverts snap-cloud/snapCloud#262

Revert "Revert "Handle Users With Duplicate Emails on the forum""

---

spambots.lua

Hello,  I have something similar this this on my website so I thought I could add to this one.
https://github.com/RiversideRocks/web-riverside/blob/master/security.php#L20

Add addtional suspicous paths

---

controllers/user.lua

Just a simple call to trim whitespace.

Add tirm to users create

---

app.lua
bin/deploy
bin/deploy_certs.sh
bin/renew-certs.sh
lib/exceptions.lua
luarocks.lock

* Updates lapis
* pass along release info to sentry
* use a lock file to ensure dependencies are in sync
* update the deploy script to reflect the use of a lockfile

Lapis updates

---

INSTALL.md

There were a lot of necessary commands and small info needed that was missing in the INSTALL.md that I had to navigate and pick and choose myself.
I added more explicit instructions to make the INSTALL.md make more sense to people new to the Snap! site and know what exactly to do

Rewritten INSTALL.md doucumentation for more explicit instructions

---

app.lua
bin/deploy_snap.sh
lib/exceptions.lua
nginx.conf.d/locations.conf
nginx.conf.d/snap-ide.conf

sets up /html/extensions to map to /extensions as a place to develop extensions
* updates /site for the new embed modal
* fixes the snap deploy script

Enhanced Embed Modal, Add extensions paths

---

cors.lua

Added TensorSnap URLs. TensorSnap provides a block-based interface to TensorFlow.js using Snap!

Add TensorSnap URLs

---

discourse.lua
validation.lua

This should just notify sentry, but not as an error.

Add Error Logging for Rate Limit issues

---

api.lua
app.lua
bin/deploy
controllers/user.lua
lib/util.lua
static/style/classes.css
validation.lua
views/bulk.etlua
views/profile.etlua
views/user_admin.etlua

There were a few remaining tasks:
* need to block students from changing emails 
* password hashing was incorrect which wouldn't allow anyone to login w/o a password reset
* Made a bunch of small tweaks to the bulk creation page
* Added the ability to paste in a CSV file too.
* Improved the dev error messages -- unexpected errors render in a modal, and are logged. 
* fix a bug with the forum error message when trying to log in. I separated GET/POST methods because the redirect action is different. 
Completely unrelated, but fix the logout redirection from the forum.

Finish Bulk Account Creation

---

.gitignore
app.lua
config.lua
cors.lua
lib/global.lua
lib/util.lua

- ignore node_modules
- update CORS, add comments for contact info
- add new NCSU domain
- Resolve redirection vuln in app default_route
- Move some utility functions to their own files

Add CORS Domain, Fix Redirect Issue

---

controllers/user.lua

Mostly so the admin view looks/works correctly.

Add additional user data to learners page

---

controllers/user.lua
site.lua
views/footer.etlua

OK, this fixes the issue where people were incorrectly seeing the message about student accounts.
Also properly validate a user exists when trying to visit the teacher pages, just so an error doesn't get thrown.
And fix the footer links+images on nested pages so they reference the right locations

Fix account login bug

---

bin/lapis-migrate
controllers/user.lua
db/init.sh
db/schema.sql
static/style/elements.css
static/style/layout.css
views/footer.etlua
views/layout.etlua
views/navigation_bar.etlua
views/partials/collection.etlua
views/partials/collection_thumbnail.etlua
views/partials/grid_search.etlua
views/partials/project.etlua
views/partials/project_buttons.etlua
views/project.etlua

* allow moderator users to make people teachers
* a bunch of smallish accessibility fixes to appease berkeley audits

Allow Mods to Make Teachers + a11y fixes

---

config.lua
static/style/project.css
views/dialogs/flag_reason.etlua
views/partials/project_buttons.etlua
views/project_bs.etlua

* fixup the display of the admin bookmarks counter
* fix the classname in the flagged notes field
* tidy project control bar css
Will deploy to staging, but this page should now be ready.

Final Tweak to Project Bootstrap Page
