snap-cloud/snapCloud

- api.lua
Seems like this should just be `created` which is already being set.
> No `joined` column on User

- app.lua
NCSU runs research branches of Snap that add additional help features. Teachers appreciate still having access to the cloud when using our versions. This PR adds our primary server, arena.csc.ncsu.edu, to the whitelist, in addition to our backup server, eliza, which is already listed.
> Add arena.csc.ncsu.edu to the whitelisted servers

- nginx.conf
This is a built-in nginx feature which reports active server stats,
most useful is the number of current connections.
When on the server you can see the data by doing `curl http://127.0.0.1/nginx_status`.
This is also what allows the amplify agent to pickup some data.
> Add a monitoring endpoint

- nginx.conf
This will allow us to always serve snap with the cloud domain -- among other things, this will make it easy to test, and when the staging server is up, it will have it default to the correct url.
Works with https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/pull/2123
> add the current domain to the <head> of snap.html

- app.lua
NCSU started a project, STEM+C, to integrate computational thinking into middle school STEM classes. Researchers run branches of Snap! to collect students interactions with the Snap! environment to improve curriculum design. Teachers appreciate still having access to the cloud when using our versions. This PR adds the primary server dedicated to the STEM+C project, stemc.csc.ncsu.edu, to the whitelist, in addition to our servers, arena and eliza, which is already listed.
> Added stemc server to domain_allowed.

- start.sh
* You should now use a `./.env` for the environment
* On a real server it should define `LAPIS_ENVIRONMENT`.
The reason for choosing `.env` is that there are a number of tools which use `.env` as the default file for local configurations. 
One of this is [Overmind](https://github.com/DarthSim/overmind) which basically just makes managing processes easier, since it can handle an app server + db and so on.
> Update start.sh to work w/ staging environment

- app.lua
Fixes #32
Extracted from #83
This makes it easy to use `capture_errors` and `yield_error`
for error handling to always return a proper response code.
It also allows any other uses of `capture_errors` to pass `on_error`
as a table key, which `capture_errors_json` strangely does not allow.
> Add improved error handling

- nginx.conf.d/locations.conf
This will make the social site default to using the same cloud domain in development or on the staging server like Snap! does.
> Add sub-filter to social site HTML

- config.lua
Michael and I have agreed to put our tests here for now: https://github.com/snap-cloud/snap-cloud-testing
However, we do need to update the config.lua since the test framework is unfortunately hard coded to look for a config environment named `test`.
> add test config

- api.lua
Use `not verified` to refresh user status.
This is because `verified` was set to false when they signed in the first time.
> Fix Checking User Verification Status

- nginx.conf.d/ssl-production.conf
These are closer to the lets encrypt default paths. 
This makes the auto-update process a bit easier to manage.
Partial fix #80
> Update SSL paths for snap-cloud.cs10

- app.lua
As much as I don't think this is a great idea, we need to remove this if we want people to use Snap<em>!</em> for robotics and be connected to their accounts. The cookie is still `httpOnly` so that's the more important part. 
Replaces #103
> Remove https restriction from cookies

- config.lua
- nginx.conf
This is due to the weird SSL errors by some school districts.
Right now we don't really have enough info to diagnose the problem.
> Log more information to nginx logs

- api.lua
- snap-cloud-beta-0.rockspec
- validation.lua
Fixes #114 
This leverages [LuaSocket's `url.escape()`](http://w3.impa.br/~diego/software/luasocket/url.html#escape) and simplifies URL generation via [Lapis's `url_for()`](http://leafo.net/lapis/reference/actions.html#request-object-methods/url_for).
> Encode username and token URL parameters

- config.lua
After we gather enough SSL info, hopefully.
We shouldn't leave this on because it will just waste space.
> Reset Error logging back to 'warn'

- nginx.conf.d/http-only.conf
$server_name represents the `default_server` when an unknown domain (like an IP address) is used to visit the Snap!Cloud.
This ensures the redirect goes to the right place. 
Fixes #100
> Redirect unknown domains to the default_server

- api.lua
- validation.lua
This makes testing this method work because busted can't see the assert methods on the global scope.
(Also, I personally find this a little nicer to read, but that's just me...)
> Tweak assert_all to pass in actual functions.

- api.lua
Fix #137 
There's no messaging that's different, but maybe that's OK. The next time they log into Snap<em>!</em> they won't need to worry about the message or any verification.
> Verify users on save

- nginx.conf.d/http-only.conf
- nginx.conf.d/locations.conf
- nginx.conf.d/ssl-production.conf
- nginx.conf.d/ssl-staging.conf
This needs to be accessible without SSL, because it needs to work before a cert is created.
(The current location breaks the renewal process, but I manually renewed the certs and we are good til Feb.)
> Move LetsEncrypt challenge location

- api.lua
We must directly compare against `cjson.null` when checking is a JSON value is null. Because this is a lua object, it is truthy. 😑 
Null values in JSON are serialized by cjson as `cjson.null` because a lua table in the array from (`{1, 2, 3...}`) cannot contain a nil value.
Discovered on the cloud.snap.berkeley.edu site.
https://forum.snap.berkeley.edu/t/project-could-not-be-saved/194/3
> Fix Nil Check for project remix id.

- api.lua
Currently this creates a remix with a null original project, which is valid in the DB.
> Check for presence of remixID

- disk.lua
The XML library we're using still returns nil when there's no content even (such as `<notes></notes>`)
> Fix #167 Part 2

- controllers/project.lua
- controllers/user.lua
We can't enable regex as a default search.
It's possible to construct regular expressions that would slow down the DB.
Ideally we should set a DB timeout limit on queries too...
> Use ILIKE not ~* for matching text

- migrations.lua
This improves the clarity of the format of migrations keys. 
I added the other recent migration of creating views, since my local db was somewhat out of sync. 
The existing databases need to have these migrations added to the list of migrations which are already run (since we are doing things somewhat out of order, and changing keys.)
To fix this run the following command. 
```
psql -d snapcloud -c "INSERT INTO lapis_migrations VALUES ('2019-01-04:0'), ('2019-01-29:0'), ('2019-02-01:0');"
```
I already ran this command on staging, and after that on the production db.
From now on, we should be able to manage all schema changes by adding a new function to this file. 😄
> Update Migrations Keys, Add Views

- nginx.conf.d/locations.conf
* handle serving files in old_site gracefully
* includes snapsource/stable as a path
* fixes all the alias routes to not need a slash.
* no longer serves the front end from /site/ but just /
> Cleanup redirects and old_site

- cors.lua
This pull request is to get the public domain for NC State's Friday Institute for Educational Innovation allowed on Snap cloud.
> Adding line to allow snapapps domain on snap cloud.

- bin/deploy
* `bin/deploy` is nicer than `bin/deploy.sh`
* In ubuntu $0 is the script name, so use $1 for the branch argument reference.
(Not really sure why this seemed to work before?)
> Rename Deploy script, correct variable ref

- config.lua
- controllers/project.lua
- disk.lua
- models.lua
- nginx.conf
* Adds a validation such that len(projectnmae) > 0
* Adds some config such that `stat` works on macOS.
* extracts this into a function for the disk module
* uses an env variable, which defaults to the GNU stat values.
* Improved error handling in `disk`.
* If the `pcall` partially fails then recover correctly.
* The file may have already been closed.
* Define yield_error (it was not defined)
* Log the error message from pcall.
**Behavior Changes**:
* Do not update notes or project name if they don't change.
* Update the database before writing files.
* (This makes the validation easier.)
* Consolidate name and notes update into one write.
* This wasn't necessary, but seems better than two write cycles.
NOTE: This means we can update the db and have updating the XML fail.
I think this is …
> Improved Error Handling for Updating Project Names and Notes

- controllers/project.lua
Should be `projectname` not `name`
> Fix Slip in Project Name XML Call

- app.lua
- helpers.lua
These get logged to Rollbar. They are mostly harmless, but this reduced some edge cases.
Fixes #211 #207 #245
> Address some minor errors

- app.lua
- helpers.lua
We should really use `tostring` so that boolean values are handled correctly.
Prefer `match` over `get` when making routes that can accept requests from multiple verbs
> Add Minor Logged Errors

- cors.lua
Updated with new SoundScope URLs: tunescope.org, soundscope-website.firebaseapp.com, tune-scope.web.app, and tune-scope.firebaseapp.com.
> Added new SoundScope URLs

- discourse.lua
- migrations.lua
- models.lua
Also puts in place an easy way to block forum logins, bans are now
sort of "synced" -- though banning a user on Snap! doesn't log them out.
* Adds a `unique_email` column to the Users table
* Sets unique_email to the email if it's actually unique
* use's the "+" trick to create a unique email with a Snap! id
* Only creates the unique email when necessary
We still need to sync current forum users by writing a script.
> Handle Users With Duplicate Emails on the forum

- bin/deploy
- bin/deploy_snap.sh
- bin/renew-certs.sh
Mostly for convenience.
Updates all 3 copies of Snap!
* main to latest tag.
* dev/ to jens' master
* previous/ to the version specified, currently 6.0.0
> Extract out Snap! deploy script.

- bin/luarocks-install-macos.sh
- bin/setup_osx.sh
Added in the missing "luarocks" brew install library and more message informing the developer of success in installation
Fixed a variable declaration, where in Macs variable declarations don't need "$", only evaluation
> Fixed MacOS install scripts with luarocks and gcc_version variable syntax

- INSTALL.md
- app.lua
Related Issue: https://github.com/snap-cloud/snapCloud/issues/277
Confirmed that setting the SameCookie attribute to "Lax" fixes the issue for development
"None" works in the deployed website (for some reason)
Tested on Chrome and Opera (both Chromium browsers)
> Change SameSite to Lax during Development in app.lua

- bin/deploy
Not sure what's up with the letsencrypt not correctly calling the deploy_certs script...
But in any event this should help out.
> Sigh, just always renew and deploy certs on app deploy

- controllers/user.lua
- models.lua
* This was not escaping correctly. :(
* Previously if a user made 2 accounts with the same email, they both got a unique email
* NOW the first account gets a "normal" email, and the second account gets a unique one.
* Calls `self:ensure_unique_email()` on User:create instead of just discourse sign in...
> Fix the shares_email_with_others function

- .gitignore
- INSTALL.md
- api.lua
- bin/lapis-migrate
- bin/luarocks-macos
- controllers/user.lua
- migrations.lua
- models.lua
- responses.lua
- validation.lua
- writeguardmuter.lua
Support Bulk Account Creation for logged in users. 
POST format:
```json:
{ 
"users": [
{
"username": "user1", "password": "password1", "email": 'OPTIONAL'
},
{ ...}
]
}
```
If an email is not provided, then the current user's email address is used. 
To be able to use this route, you must either be an admin OR have `is_teacher` set to true on your account.
This flag is probably not a permanent solution, but could work to solve immediate issues. 
* users are auto marked as verified, and we skip a welcome email
* We do track who created the user
* no UI for any of this right now. 
* We check to make sure no users exist first, otherwise use a transaction when creating accounts.
> Bulk account creation

- INSTALL.md
- bin/dump_schema.sh
- bin/lapis-migrate
- cloud.sql
- config.lua
**Separate PORT from DATABASE_URL. This allows lapis migrate to work correctly.
* no longer need the custom/hackey migrations script. bin/lapis-migrate now also dumps
the schema if running in development
* we no longer need the dump_schema file
* regen cloud.sql with the current setup
> Cleanup Database configuration

- controllers/user.lua
- models.lua
😳 
Fix adding new users to collections, improve the validations before creating users
* we should validate the data even before querying for existing users, otherwise the existing user check is confusing
* fix using `result` so the right user is added to a collection. 
In the future, it probably makes sense to write this method such that we make only 2 queries, and use bulk DB inserts.
> Final Bulk Creation PR

- site.lua
- views/partials/collection.etlua
This makes a it a little easier to embed carousels on other pages which aren't as wide.
> add a per-page filter to a collection

- Makefile
- app.lua
- models.lua
- models/banned_ips.lua
- models/collection_memberships.lua
- models/collections.lua
- models/featured_collections.lua
- models/flagged_projects.lua
- models/followers.lua
- models/projects.lua
- models/remixes.lua
- models/tokes.lua
- models/users.lua
- writeguardmuter.lua
So, this PR has no functional changes, and it is admittedly a bit unnecessary, but I do think it's helpful–both for me and hopefully others in the future. :) 
Many of our models are tiny, but I think 1 file per model is helpful, especially for the larger models of users, projects, collections. 
I'm also a fan of annotating the models (semi-)automatically which means you're always aware of what columns are defined on the actual table. 
I added a Makefile which might be an easier way to document commands than just what's in bin. The `install-deps` command could definitely be more generic....
> Annotate + Separate models in individual files

- models/users.lua
If a user has deleted the account they used with the forum, then this runs into issues...
We can check AllUsers which won't run into database constraint issues, but the interaction with discourse is still a little weird.
> Check Deleted Users for Unique Emails

- api.lua
- app.lua
- controllers/collection.lua
- db/schema.sql
- migrations.lua
- models/collections.lua
- site.lua
- views/partials/collection_info.etlua
For admins and collection owners.
* Create a short join token which can be given to users to "add themselves" to a collection 
* Create a token by clicking the button, then copy the URL
* Turn it off by deleting the token.
Mostly so that we can use this for Snap!Con. Maybe teachers will want to use it for a classroom? Or we can we use the same thing for groups.
---
With a pretty clear prompt, Co-Pilot (Chat GPT 4.1) did OK with generating many of the components, but put them all in very stupid places and doesn't understand lapis. It generated bad SQL, and invented a good handful of functions that didn't exist in lapis/snapCloud, but was reasonable at generating the HTML/JS with only mild style improvements and tweaks to how our cloud JS API is defined.
> Ability to Join a Collection via a Join Code
